In [1]:
from numpy import random
print(random.randint(1,100))
print(random.rand())


24
0.7475695112777074


In [2]:
#create n-dimensional array with random integer values
print(random.randint(100,size=(3)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))

[53 94  5]
[[39 68 95 23]
 [12 54 23 89]
 [85 67 34 53]]
[[[96 85]
  [17  4]
  [22 29]
  [91 92]]

 [[70 10]
  [31 32]
  [60 17]
  [59 86]]

 [[ 0 97]
  [ 4 29]
  [34 19]
  [60 49]]]


In [3]:
#create n-dimensional array with random floating point values
print(random.rand())
print(random.rand(3))
print(random.rand(2,3))

0.9061136659206949
[0.03877798 0.46167092 0.12542598]
[[0.53520083 0.66338833 0.94894784]
 [0.40443395 0.8702774  0.57481051]]


In [4]:
a = random.randint(100,size=(3,2)).ravel()
a

array([66, 51, 73, 54, 27, 83])

In [5]:
#single element will be selected
random.choice(a)

73

In [6]:
#for generating an array with the given shape and elements from given list
random.choice([1,2,3,4,5],size=(4,4))

array([[4, 5, 4, 5],
       [5, 1, 1, 1],
       [4, 2, 1, 4],
       [3, 3, 5, 5]])

#### pandas:
     Data manipulation,analysis and cleaning
     Tabular, Unlabelled

#### Creating a DataFrame
      using 2 dictonaries